# shortdesc= "Frontend developement in an agile team"
start= 2023-04-02
end= 2025-06-04
role= "Front dev"
company= "Akuiteo"
desc= """
  Web development of the invoice dematerialization and the sales
  section of the ERP produced by the company"""
languages= [
  "html",
  "typescript",
  "css~sass",
]
tools = [
  "Angular",
  "Material",
  "Tailwind",
  "Figma",
  "Github",
  "Postman",
  "Jenkins",
]
skills = [
  # "Creation of screens, components, services",
  "maintenance",
  "technical debt",
  "Agile SCRUM",
  "Peer programming",
  "Mob programming",
  "UI & UX",
  "Unit tests",
  "API tests",
  "technical doc",
  "libraries updates",
]
url= "https=//www.akuiteo.com/en/"
