now = true
start = 2025-09-08
role = "Front dev"
company = "Cap Gemini"
desc = "1st mission @ CNAF just started =)"
url = "https=//www.akuiteo.com/en/"
languages = [
  "html",
  "typescript",
  "css"
]
tools = [
  "Angular",
  "Bootstrap",
  "Figma",
  "Postman",
  "SonarQube",
  "Gitlab",
  "Jenkins",
]
skills = [
  "technical debt",
  "Agile SAFE",
  "UI & UX",
  "Unit tests",
  "technical doc",
  "libraries updates",
]