# start= 2025
# shortdesc= "Frontend developement in an agile team"
now = true
date = 2025-09-08
role = "Frontend developer"
company = "Cap Gemini"
desc = "1st mission @ CNAF just started =)"
url = "https=//www.akuiteo.com/en/"
languages = [
  "html",
  "typescript",
  "css"
]
tools = [
  "Angular",
  "Bootstrap",
  "Figma",
  "Postman",
  "SonarQube",
  "Gitlab",
  "Jenkins",
]
skills = []