start= 2021-06-01
end= 2021-09-01
role= "Front dev / UI&UX"
company= "Kweerty"
desc= "Creation of wireframes & mockups and Frontend development for three showcase sites"
languages = [
  "html",
  "typescript",
  "css~sass",
]
tools = [
  "Vue",
  "Figma",
  "Github",
]
skills = [
  "specs & user stories",
  "Wireframes",
  "design system",
  "interactive mockups",
  "components libraries",
]