# start= "6mon"
date= 2022-01-01
role= "Fullstack developer"
company= "SQLI"
desc= "Developement of an internal human resources management tool in an agile team"
url= "https=//www.sqli.com/fr-fr"
tools = [
  "Angular",
  "Java Spring",
  "PostGre SQL",
  "Postman",
  "Gitlab",
]
languages = [
  "html",
  "typescript",
  "css~sass",
  "java",
]
skills = [
  "Frontend performance improvements",
  "Technical debt reduction",
  "Agile SCRUM development",
  "Better interactions and animations",
  "Unit and functional tests (90% coverage)",
]