start= 2022-02-06
end= 2022-08-12
role= "Fullstack dev"
company= "SQLI"
desc= "Developement of an internal human resources management tool in an agile team"
url= "https=//www.sqli.com/fr-fr"
tools = [
  "Angular",
  "Java Spring",
  "PostGre SQL",
  "Postman",
  "Gitlab",
]
languages = [
  "html",
  "typescript",
  "css~sass",
  "java",
]
skills = [
  "performance improvements",
  "Technical debt reduction",
  "Agile SCRUM",
  "interactions and animations",
  "Unit and functional tests",
]