start= 2020-06-02
end= 2020-08-05
role= "Front dev / UI&UX"
company= "Yesouicom"
desc= "UI/UX audits and developement for the company showcase site"
languages = [
  "html",
  "javascript",
  "css",
]
tools = [
  "Vue",
  "Figma",
  "Wordpress",
]
skills = [
  "UI & UX",
  "Frontend Performance",
  "interactive mockups",
  "Wireframes",
  "Technical doc",
]
