num: 7
name: "calamina1"
url: "https://calamina1.calamina.cafe"
online: false
tech:
  tools:
  - 'vue'
  languages:
  - 'html'
  - 'scss'
  - 'typescript'
  - 'json'
  colors:
  - '#lelele'
  - '#tetete'
  fonts:
  - 'apercu mono regular'
  icons:
  - 'tabler'

description:
- One of many attemps at making a personnal website / portfolio.
