name: "consola"
url: "https://consola.calamina.cafe"
online: false
tech:
  tools:
  - 'vue'
  languages:
  - 'html'
  - 'scss'
  - 'typescript'
  colors:
  - '#lelele'
  - '#tetete'
  fonts:
  - 'apercu mono regular'
  icons:
  - 'tabler'

description:
- First startpage ever made !
