name: push
run-name: ${{ github.actor }} [push]
on: [ push ]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.0.0'

    - name: install
      run: npm ci

    - name: lint
      run: npm run lint

    - name: knip
      run: npm run knip

    - name: npm-check
      run: npm audit

    - name: build
      run: npm run build --if-present
    # - name: typecheck
    #   run: npm run typecheck
    # - run: npm test
